name: Build, Store Artifacts, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11 using Temurin
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Use Temurin instead of AdoptOpenJDK
          java-package: jdk
          architecture: x64

      # Build the Java project using Maven
      - name: Build with Maven
        run: |
          mvn clean install -DskipTests  # This should generate target/my-java-app.jar

      # Set up Docker Buildx (required for pushing multi-platform Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # Save build artifacts (optional)
      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-build-artifacts
          path: my-java-app.jar # Adjust if you're generating different output files (e.g., WAR files)
