name: Build, Store Artifacts, Build Docker Image, and Push to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11 using Temurin
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
          architecture: x64

      # Build the Java project using Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests  # Build your Java project

      # List files in target directory (for debugging)
      - name: List files in target directory
        run: ls -al target/  # Debugging to ensure the jar is created

      # Save build artifacts
      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-build-artifacts
          path: target/my-java-app-1.0-SNAPSHOT.jar  # Update the path if necessary

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored as a GitHub secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or access token stored as a GitHub secret

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t dhananjaytupe/my-java-app:latest .  # Replace with your Docker Hub username and image name 

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push dhananjaytupe/my-java-app:latest  # Replace with your Docker Hub username and image name
