name: Build, Store Artifacts, and Upload to Artifactory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11 using Temurin
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
          architecture: x64

      # Build the Java project using Maven
      - name: Build with Maven
        run: |
          mvn clean install -DskipTests  # This should generate target/my-java-app.jar

      # Save build artifacts (optional)
      - name: Save build artifacts for future workflows
        uses: actions/upload-artifact@v4
        with:
          name: java-build-artifacts
          path: target/my-java-app.jar # Path to the artifact you want to save
