name: Build and Push Java Docker Image

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: 'jdk'
          check-latest: false

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the Java project with Maven
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress -DskipTests

      # Step 5: Upload the Maven artifact (e.g., my-java-app.jar) as a GitHub artifact (v4)
      - name: Upload Maven Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-app-artifact
          path: target/my-java-app.jar  # Adjust if your jar is located elsewhere

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Download the artifact in a new step (v4)
      - name: Download Maven Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-java-app-artifact

      # Step 8: Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: . # Ensure the context includes the Dockerfile
          dockerfile: ./Dockerfile
          push: true
          tags: |
            dhananjaytupe/my-java-app:latest
            dhananjaytupe/my-java-app:${{ github.sha }}
            dhananjaytupe/my-java-app:${{ github.ref_name }}-build
